Users/josue/improving file attachment error labels
microsoft/omnichannel-chat-widget pull request #236
Opened 2023-03-21 00:17 UTC by josuhern

**Description**
I saw that there was a gap on the error alert shown to the user when a file attachmen doesn't meet the requiments, it shows the error but doesn't tell which file caused the issue
![image](https://user-images.githubusercontent.com/62082252/226492161-e62dd955-8ab9-4958-9885-b9a821b5706b.png)

**Solution Proposed**
I propose modifing the localization files to add the file name in the alert in order to make a reference about this specific file doesn't meet the requirements

**Acceptance criteria**
Show the file name that doesn't meet the requirements

**Test cases and evidence**
https://josue.blob.core.windows.net/tasks/indexv2.html
![image](https://user-images.githubusercontent.com/62082252/226711189-092f9dd8-088b-4555-818c-569c402a6c48.png)
![image](https://user-images.githubusercontent.com/62082252/226710884-32f141e0-ea4e-41ab-8548-398b9e647b0e.png)

**Pop up**
![image](https://user-images.githubusercontent.com/62082252/226710683-f5023120-c578-48ed-8f1e-a5127d64c105.png)
![image](https://user-images.githubusercontent.com/62082252/226710728-60f2a4e9-bb41-48f0-8258-211103a3bef1.png)

2023-03-21 00:36 UTC, elopezanaya commented
I suggest we limit the chars displayed in the label to avoid breaking the UI style with files with long names, by example  :  

instead of :  __this_is_a_very_very_very_very_very_very_very_long_name.xlsx__
 to
 __this_is_a_very...__

2023-03-21 00:37 UTC, elopezanaya requested changes
I suggest we limit the chars displayed in the label to avoid breaking the UI style with files with long names, by example :

instead of : this_is_a_very_very_very_very_very_very_very_long_name.xlsx
to
this_is_a_very...

2023-03-21 00:53 UTC, elopezanaya commented
add test evidence for pop-out

2023-03-21 18:48 UTC, josuhern commented
> I suggest we limit the chars displayed in the label to avoid breaking the UI style with files with long names, by example :
> 
> instead of : this_is_a_very_very_very_very_very_very_very_long_name.xlsx to this_is_a_very...

Done

2023-03-24 00:44 UTC, elopezanaya approved these changes

2023-03-24 01:00 UTC, charliewang95 commented on chat-widget/src/components/webchatcontainerstateful/webchatcontroller/middlewares/storemiddlewares/attachmentUploadValidatorMiddleware.ts
> +const textEllipsis = (str: string, maxLength = 20): string => {
Please attach screenshot proof for this change

2023-03-24 01:03 UTC, charliewang95 commented on chat-widget/src/components/livechatwidget/common/defaultProps/dummyDefaultProps.ts
> +            MIDDLEWARE_BANNER_FILE_SIZE_WITHOUT_EXTENSION_ERROR: "File {0} exceeds the allowed limit of {1} MB and please upload the file with an appropriate file extension.",
By adding {0} backward compatibility is broken. We need to clearly log this change in the Change Log, and also keep supporting the old format.

2023-03-24 01:04 UTC, charliewang95 commented on chat-widget/src/components/livechatwidget/common/defaultProps/dummyDefaultProps.ts
> +            MIDDLEWARE_BANNER_FILE_SIZE_WITHOUT_EXTENSION_ERROR: "File {0} exceeds the allowed limit of {1} MB and please upload the file with an appropriate file extension.",
Please update change log

2023-03-24 23:03 UTC, charliewang95 commented on CHANGE_LOG.md
> +- Added MIDDLEWARE_BANNER_FILE parameter `{2}` to show the user the file name when an exception occurs, also implementing standard for parameter to keep backwards compatibility
1.0.0 is already released. Put the change under the "Unreleased" -> "Added" section.

2023-03-24 23:05 UTC, charliewang95 commented on chat-widget/src/components/livechatwidget/common/defaultProps/dummyDefaultProps.ts
> +            //{2} = File name
"F" casing

2023-03-24 23:07 UTC, charliewang95 commented on chat-widget/src/components/livechatwidget/common/defaultProps/dummyDefaultProps.ts
> +            //MIDDLEWARE_BANNER_FILE parameters:
Use /* */ for multi-line comments

2023-03-24 23:07 UTC, charliewang95 commented on chat-widget/src/components/webchatcontainerstateful/common/defaultProps/defaultMiddlewareLocalizedTexts.ts
> +//MIDDLEWARE_BANNER_FILE parameters:
same here

2023-03-24 23:21 UTC, charliewang95 approved these changes

2023-03-24 23:56 UTC, merged