Expose reducer to give access to in memory runtime state
microsoft/omnichannel-chat-widget pull request #428
Opened 2024-01-19 17:56 UTC by kevinlin98z

## **Thank you for your contribution. Before submitting this PR, please include:**

### Id of the task, bug, story or other reference.

### Description
_Include a description of the problem to be solved_

## Solution Proposed
_Detail what is the solution proposed, include links to design document if required or any other document required to support the solution_

### Acceptance criteria
_Define what are the conditions to consider the PR has achieved the intended goal_

## Test cases and evidence
_Include what tests cases were considered, any evidence of testing for future references, to identify any corner cases, etc_

### Sanity Tests
-   [ ] You have tested all changes in Popout mode
-   [ ] You have tested all changes in cross browsers i.e Edge, Chrome, Firefox, Safari and mobile devices(iOS and Android)
-   [ ] Your changes are included in the [CHANGELOG](../CHANGE_LOG.md)

## A11y
- [ ] You have run the [Automated Accessibility Check](https://accessibilityinsights.io/docs/en/windows/getstarted/automatedchecks) and have no reported issues

__*Please provide justification if any of the validations has been skipped.*__

2024-01-22 20:29 UTC, nareshme2016 approved these changes

2024-01-22 23:16 UTC, elopezanaya requested changes

2024-01-22 23:16 UTC, elopezanaya commented on chat-widget/src/contexts/common/LiveChatWidgetActionType.ts
> +        Parameters:
missing documentation

2024-01-22 23:16 UTC, elopezanaya commented on chat-widget/src/contexts/createReducer.ts
> +            console.log("ADAD reducer SET_CONVERSATION_STATE to", action.payload);
remove console logs

2024-01-23 18:55 UTC, elopezanaya approved these changes

2024-01-23 19:35 UTC, merged